###

GET http://localhost:5000/api/posts/2/comments
Content-Type: application/json

###

POST http://localhost:5000/api/posts/2/comments
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNob2V3eTMyQGdtYWlsLmNvbSIsIm5pY2tuYW1lIjoiY2hvZXd5IiwiaWF0IjoxNjUwMTA1NDc0fQ.Fwg8fQvgPEcSdeYSR8OdhAFLvDRrCPH8ggzjFLNwMp4

{
  "content": "게시물 2의 댓글 2"
}

### 

PATCH http://localhost:5000/api/posts/2/comments/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNob2V3eTMyQGdtYWlsLmNvbSIsIm5pY2tuYW1lIjoiY2hvZXd5IiwiaWF0IjoxNjUwMTA1NDc0fQ.Fwg8fQvgPEcSdeYSR8OdhAFLvDRrCPH8ggzjFLNwMp4

{
  "content": "게시물 2의 댓글 1(수정)"
}

###

DELETE http://localhost:5000/api/posts/2/comments/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNob2V3eTMyQGdtYWlsLmNvbSIsIm5pY2tuYW1lIjoiY2hvZXd5IiwiaWF0IjoxNjUwMTA1NDc0fQ.Fwg8fQvgPEcSdeYSR8OdhAFLvDRrCPH8ggzjFLNwMp4


